version: '3'

services:
  main:
    image: jj-auto-backend
    networks:
        mymacvlan:
            ipv4_address: 192.168.1.10 # Optional: Assign a specific IP to this service
    ports:
      - "9999:9999/udp"
      - "4000:4000"
      - "3010:3010"
    volumes:
      - ./backend/.env:/usr/src/app/.env


networks:
  mymacvlan:
    driver: macvlan
    driver_opts:
      parent: en8 # This should be your actual network interface
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1